-- Reusable reference table of Philippine Catholic jurisdictions (dioceses, etc.).
-- Source: CBCP Jurisdictions page (user-provided CSV). Public-read so the profile
-- diocese dropdown (and anywhere else) can use the name column.
create table if not exists public.dioceses (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  type text,
  ecclesiastical_province text,
  prelate text,
  website text,
  source text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.dioceses enable row level security;
drop policy if exists "dioceses read" on public.dioceses;
create policy "dioceses read" on public.dioceses for select using (true);

insert into public.dioceses (name, type, ecclesiastical_province, prelate, website, source, sort_order) values
('Archdiocese of Manila','Archdiocese','Manila','Jose F. Cardinal Advincula, Jr.','https://rcam.org','CBCP Jurisdictions page',1),
('Diocese of Antipolo','Diocese','Manila','Ruperto C. Santos, D.D.','https://www.facebook.com/antipolodiocese','CBCP Jurisdictions page',2),
('Diocese of Cubao','Diocese','Manila','Elias L. Ayuban, Jr., CMF','https://dioceseofcubao.ph/','CBCP Jurisdictions page',3),
('Diocese of Imus','Diocese','Manila','Reynaldo G. Evangelista, D.D.','https://www.dioceseofimus.org/','CBCP Jurisdictions page',4),
('Diocese of Kalookan','Diocese','Manila','Pablo Virgilio S. Cardinal David','https://dioceseofkalookan.ph/','CBCP Jurisdictions page',5),
('Diocese of Malolos','Diocese','Manila','Dennis C. Villarojo, D.D.','https://dioceseofmalolos.ph/','CBCP Jurisdictions page',6),
('Diocese of Novaliches','Diocese','Manila','Roberto O. Gaa','https://www.facebook.com/NovalichesDiocese','CBCP Jurisdictions page',7),
('Diocese of Parañaque','Diocese','Manila','Jesse E. Mercado, D.D.','https://www.facebook.com/romancatholicdop','CBCP Jurisdictions page',8),
('Diocese of Pasig','Diocese','Manila','Mylo Hubert C. Vergara, D.D.','https://dioceseofpasig.org/','CBCP Jurisdictions page',9),
('Diocese of San Pablo','Diocese','Manila','Marcelino Antonio M. Maralit, Jr., D.D.','https://www.facebook.com/RomanCatholicLaguna','CBCP Jurisdictions page',10),
('Apostolic Vicariate of Puerto Princesa','Apostolic Vicariate','Manila','Socrates C. Mesiona, MSP, D.D.','https://www.facebook.com/AVPP.Ugnayan','CBCP Jurisdictions page',11),
('Apostolic Vicariate of Taytay - Palawan','Apostolic Vicariate','Manila','Broderick S. Pabillo, D.D.','https://www.facebook.com/taytayvicariate/','CBCP Jurisdictions page',12),
('Archdiocese of Lipa','Archdiocese','Lipa','Gilbert A. Garcera, D.D.','https://www.facebook.com/archdioceseoflipa','CBCP Jurisdictions page',13),
('Diocese of Boac','Diocese','Lipa','Edwin O. Panergo','https://www.facebook.com/DioceseofBoac','CBCP Jurisdictions page',14),
('Diocese of Calapan','Diocese','Lipa','Moises M. Cuevas','https://facebook.com/DioceseofCalapan','CBCP Jurisdictions page',15),
('Diocese of Gumaca','Diocese','Lipa','Euginius L. Cañete, MJ, D.D.','https://www.facebook.com/GumacaDiocesePH/','CBCP Jurisdictions page',16),
('Diocese of Lucena','Diocese','Lipa','Mel Rey M. Uy, D.D.','https://www.facebook.com/RCDLOfficial','CBCP Jurisdictions page',17),
('Prelature of Infanta','Territorial Prelature','Lipa','Dave D. Capucao, D.D.','https://www.facebook.com/PrelatureInfanta/','CBCP Jurisdictions page',18),
('Apostolic Vicariate of San Jose - Occidental Mindoro','Apostolic Vicariate','Lipa','Pablito M. Tagura, SVD, D.D.','https://www.facebook.com/p/Roman-Catholic-Apostolic-Vicariate-of-San-Jose-Mindoro-100079379336373/','CBCP Jurisdictions page',19),
('Archdiocese of San Fernando','Archdiocese','San Fernando (Pampanga)','Florentino G. Lavarias, D.D.','https://facebook.com/rcasfp/','CBCP Jurisdictions page',20),
('Diocese of Balanga','Diocese','San Fernando (Pampanga)','Rufino C. Sescon Jr., D.D.','https://facebook.com/balangadiocese/','CBCP Jurisdictions page',21),
('Diocese of Iba','Diocese','San Fernando (Pampanga)','Bartolome G. Santos, Jr, D.D.','https://www.facebook.com/DioceseOfIba/','CBCP Jurisdictions page',22),
('Diocese of Tarlac','Diocese','San Fernando (Pampanga)','Roberto C. Mallari, D.D.','https://dioceseoftarlac.com','CBCP Jurisdictions page',23),
('Archdiocese of Lingayen-Dagupan','Archdiocese','Lingayen-Dagupan','Socrates B. Villegas, D.D.; Fidelis B. Layog, D.D.','https://lingayendagupan.org/','CBCP Jurisdictions page',24),
('Diocese of Alaminos','Diocese','Lingayen-Dagupan','Napoleon B. Sipalay, Jr., OP','https://www.facebook.com/OfficialPageOfTheDioceseOfAlaminos/','CBCP Jurisdictions page',25),
('Diocese of Cabanatuan','Diocese','Lingayen-Dagupan','Prudencio P. Andaya, CICM, DD','https://facebook.com/dioceseofcabanatuan','CBCP Jurisdictions page',26),
('Diocese of San Fernando de La Union','Diocese','Lingayen-Dagupan','Daniel O. Presto, D.D.','https://www.facebook.com/dsfluofficial/','CBCP Jurisdictions page',27),
('Diocese of San Jose de Nueva Ecija','Diocese','Lingayen-Dagupan','Samuel N. Agcaracar, SVD, D.D.',null,'CBCP Jurisdictions page',28),
('Diocese of Urdaneta','Diocese','Lingayen-Dagupan',null,null,'Not on CBCP page - added; verify',29),
('Archdiocese of Nueva Segovia','Archdiocese','Nueva Segovia','Marlo M. Peralta, D.D.','https://www.facebook.com/ArchdioceseofNuevaSegovia/','CBCP Jurisdictions page',30),
('Diocese of Baguio','Diocese','Nueva Segovia','Rafael T. Cruz, D.D.',null,'CBCP Jurisdictions page',31),
('Diocese of Bangued','Diocese','Nueva Segovia','Leopoldo C. Jaucian, SVD, D.D.','https://facebook.com/DioceseOfBangued','CBCP Jurisdictions page',32),
('Diocese of Laoag','Diocese','Nueva Segovia','Renato P. Mayugba, D.D.','https://facebook.com/romancatholicdioceseoflaoag/','CBCP Jurisdictions page',33),
('Apostolic Vicariate of Bontoc-Lagawe','Apostolic Vicariate','Nueva Segovia','Valentin C. Dimoc, D.D.','https://facebook.com/APOSTOLICVICARIATEOFBONLAG','CBCP Jurisdictions page',34),
('Archdiocese of Tuguegarao','Archdiocese','Tuguegarao','Ricardo L. Baccay, D.D.','https://www.facebook.com/ArchdioceseofTuguegaraoOfficial/','CBCP Jurisdictions page',35),
('Diocese of Bayombong','Diocese','Tuguegarao','Jose Elmer I. Mangalinao, D.D.','https://www.facebook.com/bayombongchancery','CBCP Jurisdictions page',36),
('Diocese of Ilagan','Diocese','Tuguegarao',null,null,'Not on CBCP page - added; verify',37),
('Prelature of Batanes','Territorial Prelature','Tuguegarao','Danilo B. Ulep, D.D.','https://www.facebook.com/PrelatureOfBatanes','CBCP Jurisdictions page',38),
('Apostolic Vicariate of Tabuk','Apostolic Vicariate','Tuguegarao','Sean B. Mejia, D.D.','https://www.facebook.com/p/Apostolic-Vicariate-of-Tabuk-100094731769168/','CBCP Jurisdictions page',39),
('Archdiocese of Caceres','Archdiocese','Caceres','Rex Andrew C. Alarcon, D.D.','https://www.archdioceseofcaceres.org/','CBCP Jurisdictions page',40),
('Diocese of Daet','Diocese','Caceres','Herman G. Abcede, RCJ','https://www.facebook.com/pandayannisanjose/','CBCP Jurisdictions page',41),
('Diocese of Legazpi','Diocese','Caceres','Joel Z. Baylon, D.D.','https://www.facebook.com/DioceseofLegazpi','CBCP Jurisdictions page',42),
('Diocese of Libmanan','Diocese','Caceres','Jose R. Rojas, Jr., D.D.','https://libmanandiocese.org/','CBCP Jurisdictions page',43),
('Diocese of Masbate','Diocese','Caceres',null,null,'Not on CBCP page - added; verify',44),
('Diocese of Sorsogon','Diocese','Caceres','Jose Alan V. Dialogo, D.D.','https://facebook.com/profile.php?id=100064818847681','CBCP Jurisdictions page',45),
('Diocese of Virac','Diocese','Caceres','Luisito A. Occiano, D.D.','https://www.facebook.com/diocese.virac','CBCP Jurisdictions page',46),
('Archdiocese of Cebu','Archdiocese','Cebu','Alberto S. Uy, D.D.','https://thearchdioceseofcebu.com/','CBCP Jurisdictions page',47),
('Diocese of Dumaguete','Diocese','Cebu','Julito B. Cortes, D.D.','https://facebook.com/DumagueteDiocese','CBCP Jurisdictions page',48),
('Diocese of Maasin','Diocese','Cebu','Precioso D. Cantillas, SDB, D.D.','https://www.facebook.com/maasindiocese','CBCP Jurisdictions page',49),
('Diocese of Tagbilaran','Diocese','Cebu',null,null,'Not on CBCP page - added; verify',50),
('Diocese of Talibon','Diocese','Cebu','Patrick Daniel Y. Parcon, D.D.','https://www.facebook.com/DioceseofTalibon','CBCP Jurisdictions page',51),
('Archdiocese of Jaro','Archdiocese','Jaro','Midyphil B. Billones, D.D.','https://www.rcajaro.com/','CBCP Jurisdictions page',52),
('Diocese of Bacolod','Diocese','Jaro','Louie P. Galbines, D.D.','https://bacoloddiocese.org/','CBCP Jurisdictions page',53),
('Diocese of Kabankalan','Diocese','Jaro',null,null,'Not on CBCP page - added; verify',54),
('Diocese of San Carlos','Diocese','Jaro','Gerardo A. Alminaza, D.D.','https://www.facebook.com/SanCarlosDiocese','CBCP Jurisdictions page',55),
('Diocese of San Jose de Antique','Diocese','Jaro','Marvyn A. Maceda, D.D.','https://facebook.com/p/Diocese-of-San-Jose-de-Antique-100092227122271/','CBCP Jurisdictions page',56),
('Archdiocese of Capiz','Archdiocese','Capiz','Victor B. Bendico, D.D.',null,'CBCP Jurisdictions page',57),
('Diocese of Kalibo','Diocese','Capiz','Cyril B. Villareal, D.D.','https://www.facebook.com/dioceseofkalibo/','CBCP Jurisdictions page',58),
('Diocese of Romblon','Diocese','Capiz','Narciso V. Abellana, MSC, D.D.','https://web.facebook.com/profile.php?id=100077345437489','CBCP Jurisdictions page',59),
('Archdiocese of Palo','Archdiocese','Palo','John F. Du, D.D.','https://archdioceseofpalo.org/','CBCP Jurisdictions page',60),
('Diocese of Borongan','Diocese','Palo','Crispin B. Varquez, D.D.','http://dioceseofborongan.com/','CBCP Jurisdictions page',61),
('Diocese of Calbayog','Diocese','Palo','Isabelo C. Abarquez, D.D.','https://www.facebook.com/ECODESAMAR','CBCP Jurisdictions page',62),
('Diocese of Catarman','Diocese','Palo','Nolly C. Buco, D.D.','https://facebook.com/DioceseOfCatarman50','CBCP Jurisdictions page',63),
('Diocese of Naval','Diocese','Palo','Rex C. Ramirez, D.D.','https://facebook.com/NavalDiocese','CBCP Jurisdictions page',64),
('Archdiocese of Cagayan de Oro','Archdiocese','Cagayan de Oro','Jose A. Cabantan, D.D.','https://www.facebook.com/ascacdo','CBCP Jurisdictions page',65),
('Diocese of Butuan','Diocese','Cagayan de Oro','Cosme Damian R. Almedilla, D.D.','https://www.facebook.com/bxudiocesecommunications/','CBCP Jurisdictions page',66),
('Diocese of Malaybalay','Diocese','Cagayan de Oro','Noel P. Pedregosa','https://www.facebook.com/DioceseofMalaybalay','CBCP Jurisdictions page',67),
('Diocese of Prosperidad','Diocese','Cagayan de Oro','Ruben C. Labajo, D.D.','https://www.facebook.com/profile.php?id=61571854974328','CBCP Jurisdictions page',68),
('Diocese of Surigao','Diocese','Cagayan de Oro','Antonieto D. Cabajog, D.D.','https://dioceseofsurigao.org/','CBCP Jurisdictions page',69),
('Diocese of Tandag','Diocese','Cagayan de Oro','Raul B. Dael, D.D.','https://www.facebook.com/TandagDiocese','CBCP Jurisdictions page',70),
('Archdiocese of Cotabato','Archdiocese','Cotabato','Charlie M. Inzon, OMI','https://www.facebook.com/p/Archdiocese-of-Cotabato-61553646137260/','CBCP Jurisdictions page',71),
('Diocese of Kidapawan','Diocese','Cotabato','Jose Colin M. Bagaforo, D.D.','https://www.facebook.com/dioceseofkidapawan','CBCP Jurisdictions page',72),
('Diocese of Marbel','Diocese','Cotabato','Cerilo Alan U. Casicas, D.D.',null,'CBCP Jurisdictions page',73),
('Archdiocese of Davao','Archdiocese','Davao','Romulo G. Valles, D.D.; George B. Rimando, D.D.','http://www.archdioceseofdavao.com/','CBCP Jurisdictions page',74),
('Diocese of Digos','Diocese','Davao','Guillermo V. Afable, D.D.','https://www.facebook.com/sugidofficial/','CBCP Jurisdictions page',75),
('Diocese of Mati','Diocese','Davao','Abel C. Apigo, D.D.','https://facebook.com/theromancatholicofthedioceseofmati','CBCP Jurisdictions page',76),
('Diocese of Tagum','Diocese','Davao','Medil S. Aseo, D.D.','https://www.facebook.com/dioceseoftagumditascom','CBCP Jurisdictions page',77),
('Archdiocese of Ozamiz','Archdiocese','Ozamiz','Martin S. Jumoad, D.D.','https://www.facebook.com/ArchidioecesisOzamisanus/','CBCP Jurisdictions page',78),
('Diocese of Dipolog','Diocese','Ozamiz','Severo C. Caermare, D.D.','https://romancatholicdipolog.wordpress.com/','CBCP Jurisdictions page',79),
('Diocese of Iligan','Diocese','Ozamiz','Jose R. Rapadas III, D.D.; David William V. Antonio, D.D.','https://www.facebook.com/dioceseofiligan','CBCP Jurisdictions page',80),
('Diocese of Pagadian','Diocese','Ozamiz','Ronald Anthony P. Timoner','https://www.facebook.com/DioceseOfPagadianOfficial','CBCP Jurisdictions page',81),
('Prelature of Marawi','Territorial Prelature','Ozamiz','Edwin A. de la Peña, MSP, D.D.','https://www.facebook.com/PrelatureofMarawi','CBCP Jurisdictions page',82),
('Archdiocese of Zamboanga','Archdiocese','Zamboanga','Julius S. Tonel, D.D.','https://www.facebook.com/RCAZSoccom1910/','CBCP Jurisdictions page',83),
('Diocese of Ipil','Diocese','Zamboanga','Glenn M. Corsiga, D.D.','https://www.facebook.com/rcdioceseofipil','CBCP Jurisdictions page',84),
('Prelature of Isabela de Basilan','Territorial Prelature','Zamboanga','Leo M. Dalmao, CMF','https://facebook.com/profile.php?id=100068533110913','CBCP Jurisdictions page',85),
('Apostolic Vicariate of Jolo','Apostolic Vicariate','Zamboanga',null,null,'Not on CBCP page - added; verify',86),
('Military Ordinariate of the Philippines','Military Ordinariate','(none - directly under the Holy See)','Oscar Jaime L. Florencio, D.D.','https://www.facebook.com/MilitaryOrdinariateofthePhilippines','CBCP Jurisdictions page',87)
on conflict (name) do nothing;
